spring:
  datasource:
    url: jdbc:h2:mem:frogcrew
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          authorities-claim-name: authorities # The claim name that stores the authorities in the JWT token (the custom claim name that the JwtAuthenticationConverter should inspect).
          authority-prefix: ""

api:
  endpoint:
    base-url: /api/v1

server:
  port: 8080

# CORS configuration
cors:
  allowed-origins: http://localhost:5173,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true